// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmq.cuh"

DECL_MMQ_CASE(GGML_TYPE_IQ4_XS, float);
DECL_MMQ_CASE(GGML_TYPE_IQ4_XS, half);
DECL_MMQ_CASE(GGML_TYPE_IQ4_XS, nv_bfloat16);
