// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmq.cuh"

DECL_MMQ_CASE(GGML_TYPE_IQ2_XXS, float);
DECL_MMQ_CASE(GGML_TYPE_IQ2_XXS, half);
DECL_MMQ_CASE(GGML_TYPE_IQ2_XXS, nv_bfloat16);
