// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmq.cuh"

DECL_MMQ_CASE(GGML_TYPE_Q4_1, float);
DECL_MMQ_CASE(GGML_TYPE_Q4_1, half);
DECL_MMQ_CASE(GGML_TYPE_Q4_1, nv_bfloat16);
