// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmq.cuh"

DECL_MMQ_CASE(GGML_TYPE_MXFP4, float);
DECL_MMQ_CASE(GGML_TYPE_MXFP4, half);
DECL_MMQ_CASE(GGML_TYPE_MXFP4, nv_bfloat16);
