// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmq.cuh"

DECL_MMQ_CASE(GGML_TYPE_Q5_0, float);
DECL_MMQ_CASE(GGML_TYPE_Q5_0, half);
DECL_MMQ_CASE(GGML_TYPE_Q5_0, nv_bfloat16);
