// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../mmq.cuh"

DECL_MMQ_CASE(GGML_TYPE_IQ3_S, float);
DECL_MMQ_CASE(GGML_TYPE_IQ3_S, half);
DECL_MMQ_CASE(GGML_TYPE_IQ3_S, nv_bfloat16);
